### ISSUE TITLE
Crash when used with React Native or Expo

### ISSUE THREAD

**Issue by quocluongha** [TanStack/pacer#61]
### TanStack Pacer version

v0.16.1

### Framework/Library version

React Native v0.79.6 or Expo SDK 53

### Describe the bug and the steps to reproduce it

When I upgraded `@tanstack/react-pacer` to version `0.16.0` and above, my app crashed at bundle step.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://snack.expo.dev/@quocluong2001/expo-with-pacer

### Screenshots or Videos (Optional)

I got this error when running on Simulator.

>  ERROR  [runtime not ready]: TypeError: (0, _classPrivateFieldLooseBase2(...)_eventTarget]().addEventListener is not a function (it is undefined), js engine: hermes
 LOG  Running "QlayJobs" with {"rootTag":1,"initialProps":null,"fabric":true}
 ERROR  [runtime not ready]: Invariant Violation: "QlayJobs" has not been registered. This can happen if:
>* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
>* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

<img width="1320" height="2868" alt="Image" src="https://github.com/user-attachments/assets/aa234cde-0def-454b-a74f-d0fbabcab69b" />

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by AlemTuzlak** [comment]
@KevinVandy I think this is due to the event system added into the pacer library, I guess we would need to wrap it with a check of sorts if it's actually available?

**Comment by AlemTuzlak** [comment]
@quocluongha just released a new patch that should fix the issue, please give it a go!

**Comment by quocluongha** [comment]
@AlemTuzlak Sorry for the late response. Unforturnately the issue is still the same on the latest `@tanstack/react-pacer` release version `0.16.2`. You can modify the package version at the [Snack link above](https://snack.expo.dev/@quocluong2001/expo-with-pacer) and the issue still persist.

**Comment by AlemTuzlak** [comment]
@quocluongha thanks, seems the error is different now than before, it's due to a missing key now, will look further into it, adding { key: "test" } as a second argument seems to make it go away

**Comment by AlemTuzlak** [comment]
@quocluongha this uses JS and it doesn't tell you that the 2nd argument is actually required, if you pass in options as expected it works!

**Comment by AlemTuzlak** [comment]
Closing as the original issue is resolved!

**Comment by quocluongha** [comment]
@AlemTuzlak Thanks, it seems the issue still happens when used with bare React Native CLI. I will try to provide a reproducible repo asap.

**Comment by quocluongha** [comment]
@AlemTuzlak Sorry for the late response, here is the [reproducible repo](https://github.com/quocluongha/react-native-with-pacer) with React Native CLI. It is the exact same error, I think Expo Snack was using the different bundler than the actual development bundler, which is Metro. Thanks!

**Comment by AlemTuzlak** [comment]
Midn opening a new issue? I don't want to forget to check it out

**Comment by quocluongha** [comment]
@AlemTuzlak Sure, please relate to this [new issue](https://github.com/TanStack/pacer/issues/68)
